fetchIntervalMilliSeconds: 1000
gasMultiplier: 1.1
oracles:
  WETH/USDC:
    binance:
      period: 15
      inverval: 1s
      quote: USDT
      base: ETH
    chainlink:
      quote: USDC
      base: ETH
    onchain:
      quote: USDC
      base: WETH
markets:
  WETH/USDC:
    clober:
      quote: USDC
      base: WETH
    params:
      balancePercentage: 20
      defaultBidTickSpread: 6
      defaultAskTickSpread: 6
      orderGap: 1
      orderNum: 1
      startQuoteAmount: 386300
      startBaseAmount: 100
      maxEpochDurationSeconds: 60
      minSpongeTick: 0
      maxSpongeTick: 6
