fetchIntervalMilliSeconds: 1000
gasMultiplier: 1.1
oracles:
  WETH/USDC:
    binance:
      period: 15
      inverval: 1s
      quote: USDT
      base: ETH
    chainlink:
      quote: USDC
      base: ETH
    onchain:
      quoteAmount: 400000
      quote: USDC
      baseAmount: 100
      base: WETH
markets:
  WETH/USDC:
    clober:
      quote: USDC
      base: WETH
    params:
      balancePercentage: 20
      defaultBidTickSpread: 20
      defaultAskTickSpread: 20
      orderGap: 1
      orderNum: 1
      startQuoteAmount: 386300
      startBaseAmount: 100
      maxEpochDurationSeconds: 3600
      spongeTick: 2
