fetchIntervalMilliSeconds: 10000
gasMultiplier: 1.1
markets:
  WETH/USDC:
    binance:
      quote: USDT
      base: ETH
    clober:
      quote: USDC
      base: WETH
    params:
      defaultBaseBalance: 10
      deltaLimit: 3
      minTickSpread: 3
      maxTickSpread: 10
      orderGap: 1
      orderNum: 5
      orderSize: 1
      minOrderSize: 0.5
