fetchIntervalMilliSeconds: 1000
gasMultiplier: 1.1
markets:
  WETH/USDC:
    binance:
      quote: USDT
      base: ETH
    clober:
      quote: USDC
      base: WETH
    params:
      balancePercentage: 20
      defaultBidTickSpread: 30
      defaultAskTickSpread: 30
      orderGap: 1
      orderNum: 1
      startQuoteAmount: 386300
      startBaseAmount: 100
