fetchIntervalMilliSeconds: 1000
gasMultiplier: 1.1
markets:
  WETH/USDC:
    binance:
      quote: USDT
      base: ETH
    clober:
      quote: USDC
      base: WETH
    params:
      minTickSpread: 0
      maxTickSpread: 6
      orderGap: 1
      orderNum: 1
      orderSize: 5
      minOrderSize: 0.5
      startQuoteAmount: 37220
      startBaseAmount: 10
