fetchIntervalMilliSeconds: 1000
gasMultiplier: 1.1
markets:
  ETH/USDC:
    binance:
      quote: USDT
      base: ETH
    clober:
      quote: USDC
      base: ETH
    params:
      defaultBaseBalance: 10
      deltaLimit: 3
      minSpread: 1
      maxSpread: 10
      orderGap: 1
      orderNum: 5
      orderSize: 1
      minOrderSize: 0.5
