fetchIntervalMilliSeconds: 10000
gasMultiplier: 1.1
markets:
  WETH/USDC:
    binance:
      quote: USDT
      base: ETH
    clober:
      quote: USDC
      base: WETH
    params:
      deltaLimit: 1000
      minTickSpread: 3
      maxTickSpread: 10
      orderGap: 1
      orderNum: 1
      orderSize: 5
      minOrderSize: 0.5
      startQuoteAmount: 31000
      startBaseAmount: 10
