fetchIntervalMilliSeconds: 1000
gasMultiplier: 1.1
markets:
  WETH/USDC:
    binance:
      quote: USDT
      base: ETH
    clober:
      quote: USDC
      base: WETH
    params:
      minTickSpread: 0
      maxTickSpread: 6
      defaultBidTickSpread: 10
      defaultAskTickSpread: 10
      orderGap: 1
      orderNum: 1
      startQuoteAmount: 386300
      startBaseAmount: 100
